config/routes.rb
Rails.application.routes.draw do
  resources :cheeses

end

app/models/cheese.rb
class Cheese < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cheeses_controller.rb
class CheesesController < ApplicationController
  before_action :set_cheese, only: [:show, :edit, :update, :destroy]

  # GET /cheeses
  # GET /cheeses.json
  def index
    @cheeses = Cheese.all
  end

  # GET /cheeses/1
  # GET /cheeses/1.json
  def show
  end

  # GET /cheeses/new
  def new
    @cheese = Cheese.new
  end

  # GET /cheeses/1/edit
  def edit
  end

  # POST /cheeses
  # POST /cheeses.json
  def create
    @cheese = Cheese.new(cheese_params)

    respond_to do |format|
      if @cheese.save
        format.html { redirect_to @cheese, notice: 'Cheese was successfully created.' }
        format.json { render :show, status: :created, location: @cheese }
      else
        format.html { render :new }
        format.json { render json: @cheese.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cheeses/1
  # PATCH/PUT /cheeses/1.json
  def update
    respond_to do |format|
      if @cheese.update(cheese_params)
        format.html { redirect_to @cheese, notice: 'Cheese was successfully updated.' }
        format.json { render :show, status: :ok, location: @cheese }
      else
        format.html { render :edit }
        format.json { render json: @cheese.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cheeses/1
  # DELETE /cheeses/1.json
  def destroy
    @cheese.destroy
    respond_to do |format|
      format.html { redirect_to cheeses_url, notice: 'Cheese was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cheese
      @cheese = Cheese.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cheese_params
      params.require(:cheese).permit(:type, :name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cheeses_helper.rb
module CheesesHelper
end

app/views/cheeses/_form.html.erb
<%= form_for(@cheese) do |f| %>
  <% if @cheese.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cheese.errors.count, "error") %> prohibited this cheese from being saved:</h2>

      <ul>
      <% @cheese.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cheeses/edit.html.erb
<h1>Editing Cheese</h1>

<%= render 'form' %>

<%= link_to 'Show', @cheese %> |
<%= link_to 'Back', cheeses_path %>

app/views/cheeses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cheeses</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cheeses.each do |cheese| %>
      <tr>
        <td><%= cheese.type %></td>
        <td><%= cheese.name %></td>
        <td><%= cheese.image %></td>
        <td><%= link_to 'Show', cheese %></td>
        <td><%= link_to 'Edit', edit_cheese_path(cheese) %></td>
        <td><%= link_to 'Destroy', cheese, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cheese', new_cheese_path %>

app/views/cheeses/new.html.erb
<h1>New Cheese</h1>

<%= render 'form' %>

<%= link_to 'Back', cheeses_path %>

app/views/cheeses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @cheese.type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @cheese.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @cheese.image %>
</p>

<%= link_to 'Edit', edit_cheese_path(@cheese) %> |
<%= link_to 'Back', cheeses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crackthewheel</title>
  <script src="build/react.js"></script>
  <script src="build/JSXTransformer.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
≈
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

<html>
  <head>

  </head>
  <body>
    <div id="mount-point"></div>
    <script type="text/jsx">
      // React Code Goes Here
    </script>
  </body>
</html>